#!/bin/bash
#
#	 Copyright (C) 2022 Skeletonek
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#    Contact: skeleton0199@gmail.com

if [[ $1 = "-h" ]] ; then
cat << EOF
Script to update your system automaticly

Syntax: ssu [-h/s/r/v]
Options:
  -h    Shows this help
  -s    Shutdowns system after update
  -r    Restarts system after update
  -v    Shows version info
EOF
elif [[ $1 = "-v" ]] ; then
cat << EOF
Simple System Update
Version: 1.0.0
Author: Skeletonek

Copyright (C) 2022 Skeletonek
Licensed under GNU GPLv3
EOF
else
    #    Updating system
    type dnf &>/dev/null && sudo dnf update -y
    type apt &>/dev/null && sudo apt upgrade -y
    type pacman &>/dev/null && sudo pacman -Syu
    type flatpak &>/dev/null && flatpak update -y
    type snap &>/dev/null && sudo snap update -y

    #    Turning off system
    if [[ $1 = "-r" ]] ; then
        qdbus org.kde.Shutdown /Shutdown logoutAndReboot || dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Reboot" boolean:true
    elif [[ $1 = "-s" ]] ; then
        qdbus org.kde.Shutdown /Shutdown logoutAndShutdown || dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.PowerOff" boolean:true
    elif [[ $1 = "" ]] ; then
        qdbus org.kde.Shutdown /Shutdown logoutAndShutdown || dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.PowerOff" boolean:true
    fi
fi
